// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alewbnoenmvapwbbahrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsZXdibm9lbm12YXB3YmJhaHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODQ3MDQsImV4cCI6MjA2NDM2MDcwNH0.RvngI9hXJhvEWsaqVaCwoMmcDaj8boPi-vsi05RBf40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);